### ISSUE TITLE
Error when trying to bind to port

### ISSUE THREAD

**Issue by lukasitaly** [jovandeginste/workout-tracker#175]
Port 8080 is not free, so I had to use 8070. But I'm having issues. I've tried everything I know and tried researching, but the issue doesn't seem to go away. When following the guide, I get a blank page "Unable to connect". 

I tried:
- Without workout-tracker.yaml
- With workout-tracker.yaml
- With "WT_BIND" in compose.yaml
- With "bind" in workout-tracker.yaml
- With "jwt_encryption_key" in workout-tracker.yaml
- Using "0.0.0.0:8070" instead of "[::]:8070" in both "WT_BIND" and "bind"

- Port 8070 is free
- Firewall doesn't block

When I use "WT_BIND" and/or "bind" I finally get an error:  
panic: listen tcp: address "[::]:8070": too many colons in address

How can I proceed? Thanks in advance

**Comment by jovandeginste** [comment]
I'm not sure I understand what you try to achieve.

You say port 8080 is already in use, but you also use compose.yaml, which implies a Docker container.

If you don't use Docker, and simply run the binary, you can use this:

```bash
WT_BIND="[::]:8070" ./workout-tracker
```

The output should contain a line similar to this (note the `[::]:8070`:

```text
2:52PM INF Starting web server on [::]:8070 app=workout-tracker version=local sha=local module=app
```

If you use a compose file and Docker, you can simply use a different port in the `host port` part:

```yaml
version: "3.8"
services:
  workout-tracker:
    image: ghcr.io/jovandeginste/workout-tracker:master
    restart: unless-stopped
    ports:
      # Host Port:Container Port
      - 8070:8080 # This is where we define the port mapping
    volumes:
      - ./data:/data
    environment:
      - WT_JWT_ENCRYPTION_KEY=my-secret-key
```

If you prefer to use the same port inside and outside of the container, you can use this:


```yaml
version: "3.8"
services:
  workout-tracker:
    image: ghcr.io/jovandeginste/workout-tracker:master
    restart: unless-stopped
    ports:
      # Host Port:Container Port
      - 8070:8070 # This is where we define the port mapping
    volumes:
      - ./data:/data
    environment:
      - WT_JWT_ENCRYPTION_KEY=my-secret-key
      - WT_BIND="[::]:8070"
```
