### ISSUE TITLE
Extremely slow Sqlite queries with Docker

### ISSUE THREAD

**Issue by wbste** [jovandeginste/workout-tracker#392]
Hey, just wanted to document my issues here, looking for ways to help troubleshoot. Running docker desktop via wsl2 on a windows host. I'm the only user. I am using bind mounts to the host, and I know there could be some slight deltas in performance, but the many other containers I run all do the same binding and I've had no issues.

compose file:

```yaml
services:
    workout-tracker:
        ports:
            - 3065:8080
        environment:
            - WT_JWT_ENCRYPTION_KEY=my-secret-key
        volumes:
            - ./data:/data
            - ./imports:/imports
        image: ghcr.io/jovandeginste/workout-tracker:master
        restart: unless-stopped
```

Every sqlite interaction is incredibly slow. Below are some snippets from it just restarting. I use watchtower to auto-update, so I'm always on the latest version.

```
    time=2025-01-11T05:54:59.835735518Zlevel=INFOmsg=Connecting to the database 'sqlite': ./database.dbapp=workout-trackerversion=mastersha=299b7bd058c33a219c3510e53532c584ffa9bd11module=app

    time=2025-01-11T05:56:33.246399831Zlevel=WARNmsg=slow sql query [1m33.230235416s >= 100ms]app=workout-trackerversion=mastersha=299b7bd058c33a219c3510e53532c584ffa9bd11module=databaseslow_query=truequery=DELETE FROM `map_data_details` WHERE map_data_id IN (SELECT map_data_id FROM map_data_details as mdd where map_data_details.created_at < mdd.created_at)duration=93230235416rows=0file=/app/pkg/database/gorm.go:97

    time=2025-01-11T05:57:06.107303007Zlevel=WARNmsg=slow sql query [32.362159138s >= 100ms]app=workout-trackerversion=mastersha=299b7bd058c33a219c3510e53532c584ffa9bd11module=databaseslow_query=truequery=SELECT * FROM `map_data_details` WHERE `map_data_details`.`map_data_id` IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18...)duration=32362159138rows=787file=/app/pkg/database/workouts.go:407
```

Any thoughts on where to start?
