### ISSUE TITLE
wt-app won't start after update to 2.0.3

### ISSUE THREAD

**Issue by alternativesurfer** [jovandeginste/workout-tracker#417]
Hi, 

I updated to 2.0.3 and now the front-end won't start.
DB starts successfully.
App:
wt-app  | {"time":"2025-01-28T10:34:38.233113009-08:00","level":"ERROR","msg":"json: unsupported value: +Inf","app":"workout-tracker","version":"master","sha":"58bd7163ba14e0555c03bd7e599b98641fa2e2a5","module":"database","error":"json: unsupported value: +Inf","query":"SELECT * FROM \"map_data\" WHERE \"map_data\".\"workout_id\" IN (174,173,172,171,8,2,3,1,6,170,169,168,167,166,165,164,163,162,161,160,159,158,4,157,156,155,154,153,152,151,150,149,148,147,146,144,143,142,145,141,140,139,138,137,136,135,134,133,132,131,130,129,127,126,125,124,123,122,121,120,119,118,117,116,115,114,113,128,112,111,110,109,108,107,106,105,104,103,102,101,100,99,98,97,96,95,94,93,92,91,90,89,88,87,86,85,84,83,82,81,80,79,78,77,76,75,74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59,58,57,56,53,52,51,49,50,44,42,41,40,38,35,34,33,31,30,29,28,55,18,17,16,19,13,21,11,9,10)","duration":8157027,"rows":152,"file":"/app/pkg/database/workouts.go:409"}
wt-app  | {"time":"2025-01-28T10:34:38.233156396-08:00","level":"ERROR","msg":"json: unsupported value: +Inf","app":"workout-tracker","version":"master","sha":"58bd7163ba14e0555c03bd7e599b98641fa2e2a5","module":"database","error":"json: unsupported value: +Inf","query":"SELECT * FROM \"workouts\" ORDER BY date DESC","duration":10287490,"rows":152,"file":"/app/pkg/database/workouts.go:409"}
wt-app  | panic: json: unsupported value: +Inf
wt-app  |
wt-app  | goroutine 1 [running]:
wt-app  | main.main()
wt-app  |       /app/cmd/workout-tracker/main.go:30 +0x19a
wt-app exited with code 2

compose is the default provided except I changed my restart action to "always".

```
services:
  workout-tracker:
    image: ghcr.io/jovandeginste/workout-tracker:master
    container_name: wt-app
    restart: always
    ports:
      # Host Port:Container Port
      - 8080:8080
    networks:
      - workout-tracker
    env_file:
      - postgres.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: wt-db
    restart: always
    shm_size: 128mb
    volumes:
      # Store database files in a local directory.
      - ./data:/var/lib/postgresql/data
    networks:
      - workout-tracker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - postgres.env

networks:
  workout-tracker:
    external: false
```
